app:
  excel:
    resource: "https://www.predistribuce.cz/Files/potrebuji-zaridit/stav-hdo/aktualni-program-hdo-ke-stazeni/"
    location:
      valid_from:
        row: 0
        column: 12
      valid_to:
        row: 1
        column: 12
      command_number_column: 0
      first_tariff_row: 3
      day_column: 3
      row_period: 8
      on_columns: [ 4,6,8,10,12,14,16,18 ]
      off_columns: [ 5,7,9,11,13,15,17,19 ]
    days:
      monday: "pondělí"
      tuesday: "úterý"
      wednesday: "středa"
      thursday: "čtvrtek"
      friday: "pátek"
      saturday: "sobota"
      sunday: "neděle"
      holiday: "svátek"

server:
  port: 3001